apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: enforcer-k8s
webhooks:
  - admissionReviewVersions: ["v1", "v1beta1"]
    matchPolicy: Equivalent # default
    failurePolicy: Fail # default
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lVY0lsanYzUVRsK28xdFMvb0FidGhFb3JMMjFRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0VqRVFNQTRHQTFVRUF3d0hVbTlrWlNCRFFUQWVGdzB5TVRBME1UVXhOakUzTXpaYUZ3MHlNVEExTVRVeApOakUzTXpaYU1CSXhFREFPQmdOVkJBTU1CMUp2WkdVZ1EwRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdnZ0VLQW9JQkFRRFZDYmNXb2I1aUJueHp6V3U2UnFBQis4OFJ6TWJUa3dacVdWZURuS1FIZWtaZ0NLakYKZVczdFpqWmxMZVRiYlVWTnVtUkxFTFBPQTQ1OFhha0tmT2tCYmVlU1IyeTZQZE1LTHpsSitsUjQ2Y0RySGFSWApuMUo5Vm9QNEtyR3NRNW8xRWxHdEFzNGtmZ0FRRDBXRG5zT3hnRHhYN3JCZ21HaFVnZFk0cCtlNFcxNzZRcmZOCkg5UDcyTUF0UVd1V1hkYUtaYzEwL0FsbkN1MENGbUt3OXNqUVdVUllSNnVzOE42UEp1UWNtMnR6UUdxWk0wYUgKcHV2OVRzR21OTWU4OS9LUmNqZWxDbmdlMzlqaUhOeFE3SzVSQjliMEJOTmNCcjVsb2RhbTJlY3hvaTJWY0IrQwptK09WbFcyOVJTVFE0U3paNWpGZWV2a0doWGxTK2IxRVhyaTlBZ01CQUFHalV6QlJNQjBHQTFVZERnUVdCQlRnCk1ZOTZqMUdzZTAvRUJpNVowZDFoR0l3NlF6QWZCZ05WSFNNRUdEQVdnQlRnTVk5NmoxR3NlMC9FQmk1WjBkMWgKR0l3NlF6QVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTNJbXRBVXhZdgowbGFWd0N2Q0F0TmJteWlRNmNteEZIbG9xUWJjaTdNVW5hdkl1QVBpb1pMeklVNS9PU3plbitIV3laOWo1SUF3CmVWekpBWWtNQWdNcmZVU3ExWWFwQW1WVWNHWHFWdWZKMzB1ZWhKZDVZdEFUdU9wV0VnbEYzOER0enJzc3NONkgKcis0SnRpdjdPMHkrYVBPZnNXV3RkZ0xOTS9ZdWZoVjNIak9nSzBHRmFTcXpUVEZxbXBSNGx4blV0WkoxdXlndAppdy9JbldiODlMVjQ0bE9BZTVoWXFySzdIdzRFVFUvcVhyQlNyemtpdGlHUzE5d0pjMnVjSDhIdWJFQVl2MnFqCnBQTS9IQklTMEk3TERBQVlOV3FxS3hjaWFSbUhyR3lJNm9aQ3lwNzl1SFpDamhPOGovZnIrSnFIN3lUbWNScGYKYnFpNU5sMTFoL0h0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: enforcer-k8s
        namespace: default
        port: 8001
    name: "k8s-enforcer.rode.io"
    sideEffects: None
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"
#    namespaceSelector:
#      matchExpressions:
#        - key: "name"
#          operator: In
#          values:
#            - "test"